language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

before_install:
  - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran

install:
  - easy_install -U distribute
  - pip install numpy
  - pip install scipy==0.13.2
  - pip install matplotlib
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:  python setup.py test
